# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "WCAG As Used In International Law"
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  WCAG International Law.
baseurl: "/wcaginlaw" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
twitter:
  username: Myndex
author: Myndex
exclude:
  - "_external"
  - "Gemfile"
  - "Gemfile.lock"
  - "w3c.json"
# Build settings
markdown: kramdown
kramwdown:
#  toc_levels: 2..3
  input: GFM
  syntax_highlighter: rouge
highlighter: rouge
repository: Myndex/wcaginlaw

ytkey: AIzaSyCiZ9uToWu9jb7BTx47NtzCvmGGXKXp8nI

remote_theme: Myndex/websitewizard

collections:
  policies:
#    area: "Plan & Manage"
    name: "Web Accessibility Laws & Policies"
    shortname: "International<br>Laws & Policies"
    icon: "book" # TODO
    repostitory: Myndex/wcaginlaw
    output: true
    acknowledgements: false
    permalink: /:collection/:path/
    footer: |
      <p><strong>Date:</strong> Updated ---inprocess---.</p>

defaults:
  -
    scope:
      path: "_policies"
    values:
      layout: "policy"

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-include-cache
  - jekyll-remote-theme
  - wai-website-plugin
